/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.util.Collections;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Ceramic;
import model.Check;
import model.DanhSachQuanLy;
import model.DateLastestComparator;
import model.DateOldestComparator;
import model.Electronic;
import model.FileHandle;
import model.Food;
import model.FormatDate;
import model.FormatNumber;
import model.InvenDecreaseComparator;
import model.InvenIncreaseComparator;
import model.PriceDecreaseComparator;
import model.PriceIncreaseComparator;
import model.SerialDecreaseComparator;
import model.SerialIncreaseComparator;
import model.Stuff;
import model.TypeDComparator;
import model.TypeIComparator;

/**
 *
 * @author HnivGnauq
 */
public class ShowFrm extends javax.swing.JFrame {
    private DefaultTableModel tblModel;
    private int selectedIndex;
    private long min, max;
    private Date oldDate = null, lastDate = null;
    private String serial = null;
    
    private HomeFrm home;
    /**
     * Creates new form ShowFrm
     */
     public ShowFrm(){
        initComponents();
        setLocationRelativeTo(null);
        tblModel = (DefaultTableModel) showTbl.getModel();
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        showTbl.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
        showTbl.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        showTbl.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
        showTbl.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        fillToTable();
    }
     
     
    public void fillToTable() {
        tblModel.setRowCount(0);
        for (Stuff stuff : DanhSachQuanLy.list) {
            Object[] rowData = {stuff.getType(),stuff.getName(),stuff.getSerialString(),stuff.getImportPriceString(),stuff.getInventoryString(),stuff.getImportDateString()};
            tblModel.addRow(rowData);
        }
        tblModel.fireTableDataChanged();
        totalPriceUpdate();
        totalStuffUpdate();
    }
    
    private void totalPriceUpdate()
    {
        long totalPrice = 0;
        for (Stuff stuff : DanhSachQuanLy.list) {
            totalPrice += stuff.getTotalPrice();
        }
        totalPriceTxt.setText(FormatNumber.formatNumString(totalPrice));
    }
    
    private void totalStuffUpdate()
    {
        totalStuffTxt.setText(Stuff.getTotalStuff()+"");
        foodStuffTxt.setText(Food.getFoodStuff()+"");
        ceramicStuffTxt.setText(Ceramic.getCeramicStuff()+"");
        electronicStuffTxt.setText(Electronic.getElectronicStuff()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        importBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        typeSortIBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        typeSortDBtn = new javax.swing.JButton();
        serialSortDBtn4 = new javax.swing.JButton();
        serialSortIBtn3 = new javax.swing.JButton();
        priceSortDBtn5 = new javax.swing.JButton();
        priceSortIBtn4 = new javax.swing.JButton();
        invenSortDBtn6 = new javax.swing.JButton();
        invenSortIBtn5 = new javax.swing.JButton();
        dateSortDBtn7 = new javax.swing.JButton();
        dateSortIBtn6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showTbl = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalStuffTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        foodStuffTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ceramicStuffTxt = new javax.swing.JTextField();
        electronicStuffTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        minTxt = new javax.swing.JTextField();
        maxTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        priceSearchBtn = new javax.swing.JButton();
        oldTxt = new javax.swing.JTextField();
        lastTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dateSearchBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        typeSearchBtn = new javax.swing.JButton();
        typeChoiceBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh sách sản phẩm ");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Actions-document-edit-icon-16.png"))); // NOI18N
        editBtn.setText("Chỉnh sửa");
        editBtn.setPreferredSize(new java.awt.Dimension(105, 30));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        importBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/open-file-icon-16.png"))); // NOI18N
        importBtn.setText("Nhập kho");
        importBtn.setPreferredSize(new java.awt.Dimension(105, 30));
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home-icon-16.png"))); // NOI18N
        backBtn.setText("Quay lại");
        backBtn.setPreferredSize(new java.awt.Dimension(105, 30));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        exportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/open-file-icon-16.png"))); // NOI18N
        exportBtn.setText("Xuất kho");
        exportBtn.setPreferredSize(new java.awt.Dimension(105, 30));
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Actions-edit-delete-icon-16.png"))); // NOI18N
        deleteBtn.setText("Xóa");
        deleteBtn.setMaximumSize(new java.awt.Dimension(102, 22));
        deleteBtn.setMinimumSize(new java.awt.Dimension(102, 22));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(importBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon-24.png"))); // NOI18N
        searchBtn.setMnemonic(KeyEvent.VK_ENTER);
        searchBtn.setText("Tìm kiếm");
        searchBtn.setToolTipText("alt+Enter để tìm kiếm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchTxt.setToolTipText("Nhập mã hàng");
        searchTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchTxtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTxt))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        typeSortIBtn.setText("Tăng");
        typeSortIBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeSortIBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Loại");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mã hàng");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Giá");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tồn kho");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ngày");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sắp xếp");
        jLabel7.setToolTipText("");

        typeSortDBtn.setText("Giảm");
        typeSortDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeSortDBtnActionPerformed(evt);
            }
        });

        serialSortDBtn4.setText("Giảm");
        serialSortDBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialSortDBtn4ActionPerformed(evt);
            }
        });

        serialSortIBtn3.setText("Tăng");
        serialSortIBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialSortIBtn3ActionPerformed(evt);
            }
        });

        priceSortDBtn5.setText("Giảm");
        priceSortDBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSortDBtn5ActionPerformed(evt);
            }
        });

        priceSortIBtn4.setText("Tăng");
        priceSortIBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSortIBtn4ActionPerformed(evt);
            }
        });

        invenSortDBtn6.setText("Giảm");
        invenSortDBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invenSortDBtn6ActionPerformed(evt);
            }
        });

        invenSortIBtn5.setText("Tăng");
        invenSortIBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invenSortIBtn5ActionPerformed(evt);
            }
        });

        dateSortDBtn7.setText("Giảm");
        dateSortDBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateSortDBtn7ActionPerformed(evt);
            }
        });

        dateSortIBtn6.setText("Tăng");
        dateSortIBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateSortIBtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeSortIBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeSortDBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serialSortIBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(serialSortDBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceSortIBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priceSortDBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(invenSortIBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invenSortDBtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateSortIBtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateSortDBtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeSortIBtn)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(typeSortDBtn)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceSortIBtn4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(priceSortDBtn5))))
                    .addComponent(serialSortIBtn3)
                    .addComponent(invenSortIBtn5)
                    .addComponent(dateSortIBtn6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serialSortDBtn4)
                            .addComponent(invenSortDBtn6)
                            .addComponent(dateSortDBtn7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        showTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại", "Tên hàng hóa", "Mã hàng", "Giá nhập", "Số lượng tồn", "Ngày nhập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(showTbl);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Tổng số hàng trong kho:");

        totalStuffTxt.setEditable(false);

        jLabel8.setText("Tổng giá trị của kho:");

        totalPriceTxt.setEditable(false);

        jLabel11.setText("Thực phẩm");

        foodStuffTxt.setEditable(false);

        jLabel12.setText("Sành sứ");

        ceramicStuffTxt.setEditable(false);

        electronicStuffTxt.setEditable(false);

        jLabel13.setText("Đồ điện tử");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalStuffTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPriceTxt))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ceramicStuffTxt)
                            .addComponent(foodStuffTxt)
                            .addComponent(electronicStuffTxt))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalStuffTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(foodStuffTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ceramicStuffTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(electronicStuffTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        minTxt.setText("0");
        minTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minTxtMouseClicked(evt);
            }
        });

        maxTxt.setText("99999999");
        maxTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxTxtMouseClicked(evt);
            }
        });

        jLabel9.setText("Min");

        jLabel10.setText("Max");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tìm theo khoảng giá");

        priceSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon-24.png"))); // NOI18N
        priceSearchBtn.setText("Tìm kiếm");
        priceSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSearchBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Từ ngày");

        jLabel19.setText("Đến ngày");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Tìm theo ngày");

        dateSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon-24.png"))); // NOI18N
        dateSearchBtn.setText("Tìm kiếm");
        dateSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateSearchBtnActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Tìm theo loại");

        jLabel22.setText("Loại");

        typeSearchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon-24.png"))); // NOI18N
        typeSearchBtn.setText("Tìm kiếm");
        typeSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeSearchBtnActionPerformed(evt);
            }
        });

        typeChoiceBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại", "Thực phẩm", "Sành sứ", "Đồ điện tử" }));
        typeChoiceBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeChoiceBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(minTxt)
                                    .addComponent(maxTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(oldTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(lastTxt)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(dateSearchBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(priceSearchBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(typeChoiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(typeSearchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceSearchBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateSearchBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(typeChoiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeSearchBtn))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        selectedIndex = showTbl.getSelectedRow();
        if(DanhSachQuanLy.list.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Hãy nhập thêm hàng hóa rồi sửa!");
        } else if(selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Hãy chọn dòng hàng hóa cần sửa rồi ấn Sửa!");
        } else { // chon dong can sua va nhan nut
            EditFrm editFrm = new EditFrm(DanhSachQuanLy.list.get(selectedIndex).getSerialString());
            editFrm.setEditData(DanhSachQuanLy.list.get(selectedIndex));
            editFrm.setVisible(true);
            dispose();
        }// TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        ImportFrm importFrm = new ImportFrm(home,rootPaneCheckingEnabled);
        importFrm.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_importBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        try {
            FileHandle.saveFile();
        } catch (Exception ex) {
            Logger.getLogger(ShowFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
        HomeFrm homeFrm = new HomeFrm();
        homeFrm.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        selectedIndex = showTbl.getSelectedRow();
        if(DanhSachQuanLy.list.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Hãy nhập thêm hàng hóa rồi Xuất kho!!!");
        } else if(selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Hãy chọn dòng hàng hóa cần xuất rồi ấn Xuất kho!!!");
        } else { // chon dong can sua va nhan nut
            ExportFrm exportFrm = new ExportFrm(DanhSachQuanLy.list.get(selectedIndex).getSerialString());
            exportFrm.setExportData(DanhSachQuanLy.list.get(selectedIndex));
            exportFrm.setVisible(true);
            dispose();
        }// TODO add your handling code here:
    }//GEN-LAST:event_exportBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        boolean isOK = true;
        isOK = serialTxtProcess();
        if(isOK) {
            EditFrm edit = new EditFrm(serial);
            for (Stuff stuff : DanhSachQuanLy.list) {
                if(stuff.getSerialString().equalsIgnoreCase(serial)) {
                    edit.setEditData(stuff);
                    break;
                }     
            }
            edit.setVisible(true);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void priceSortIBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSortIBtn4ActionPerformed
        Collections.sort(DanhSachQuanLy.list, new PriceIncreaseComparator());
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_priceSortIBtn4ActionPerformed

    private void typeSortIBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeSortIBtnActionPerformed
        Collections.sort(DanhSachQuanLy.list, new TypeIComparator());
        fillToTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_typeSortIBtnActionPerformed

    private void typeSortDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeSortDBtnActionPerformed
        Collections.sort(DanhSachQuanLy.list, new TypeDComparator());
        fillToTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_typeSortDBtnActionPerformed

    private void serialSortIBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialSortIBtn3ActionPerformed
        Collections.sort(DanhSachQuanLy.list, new SerialIncreaseComparator());
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_serialSortIBtn3ActionPerformed

    private void serialSortDBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialSortDBtn4ActionPerformed
        Collections.sort(DanhSachQuanLy.list, new SerialDecreaseComparator());
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_serialSortDBtn4ActionPerformed

    private void priceSortDBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSortDBtn5ActionPerformed
        Collections.sort(DanhSachQuanLy.list, new PriceDecreaseComparator());
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_priceSortDBtn5ActionPerformed

    private void dateSortIBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateSortIBtn6ActionPerformed
        Collections.sort(DanhSachQuanLy.list, new DateOldestComparator());
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_dateSortIBtn6ActionPerformed

    private void dateSortDBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateSortDBtn7ActionPerformed
        Collections.sort(DanhSachQuanLy.list, new DateLastestComparator());
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_dateSortDBtn7ActionPerformed

    private void invenSortIBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invenSortIBtn5ActionPerformed
        Collections.sort(DanhSachQuanLy.list, new InvenIncreaseComparator());
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_invenSortIBtn5ActionPerformed

    private void invenSortDBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invenSortDBtn6ActionPerformed
        Collections.sort(DanhSachQuanLy.list, new InvenDecreaseComparator());
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_invenSortDBtn6ActionPerformed

    private void searchTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTxtMousePressed
        fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_searchTxtMousePressed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        selectedIndex = showTbl.getSelectedRow();
        if(DanhSachQuanLy.list.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Hãy nhập thêm hàng hóa rồi sửa!");
        } else if(selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Hãy chọn dòng hàng hóa muốn xóa rồi Ấn Xóa!!!");
        } else { // chon dong can sua va nhan nut
            int click = JOptionPane.showConfirmDialog(rootPane, "Bạn chọn xóa hàng hóa này!!!");
            if(click == JOptionPane.YES_OPTION);
            {
               DanhSachQuanLy.list.remove(DanhSachQuanLy.list.get(selectedIndex));
               Stuff.setTotalStuff(Stuff.getTotalStuff()- 1);
               JOptionPane.showMessageDialog(rootPane, "Xóa thành công!!!");
            }
            fillToTable();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void typeChoiceBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeChoiceBoxItemStateChanged
//        if(typeChoiceBox.getSelectedItem().equals("Thực phẩm")) {
//            serial = new Serial("FD", Food.getCountFD());
//            serialTxt.setText(serial.getSerial());
//        } else
//        if(typeChoiceBox.getSelectedItem().equals("Sành sứ")) {
//            serial = new Serial("CM", Ceramic.getCountCM());
//            serialTxt.setText(serial.getSerial());
//        } else
//        if(typeChoiceBox.getSelectedItem().equals("Đồ điện tử")) {
//            serial = new Serial("EC", Electronic.getCountEC());
//            serialTxt.setText(serial.getSerial());
//        } else
//        serialTxt.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_typeChoiceBoxItemStateChanged

    private void maxTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxTxtMouseClicked
        maxTxt.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_maxTxtMouseClicked

    private void minTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minTxtMouseClicked
        minTxt.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_minTxtMouseClicked

    private void priceSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSearchBtnActionPerformed
        boolean isOK = true;
        isOK = minTxtProcess();
        isOK = maxTxtProcess();
        if(isOK) {
            SearchFrm searchFrm = new SearchFrm(min, max);
            searchFrm.setVisible(true);
            minTxt.setText("0");
            maxTxt.setText("99999999");
        }// TODO add your handling code here:
    }//GEN-LAST:event_priceSearchBtnActionPerformed

    private void dateSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateSearchBtnActionPerformed
        boolean isOK = true;
        isOK = oldDateTxtProcess();
        isOK = lastDateTxtProcess();
        if(isOK) {
            SearchFrm searchFrm = new SearchFrm(oldDate, lastDate);
            searchFrm.setVisible(true);
            oldTxt.setText("");
            lastTxt.setText("");
        }// TODO add your handling code here:
    }//GEN-LAST:event_dateSearchBtnActionPerformed

    private void typeSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeSearchBtnActionPerformed
        boolean isOK = true;
        isOK = typeChoiceProcess();
        if(isOK) {
            SearchFrm searchFrm = new SearchFrm((String)typeChoiceBox.getSelectedItem());
            searchFrm.setVisible(true);
            typeChoiceBox.setSelectedItem("Loại");
        }// TODO add your handling code here:
    }//GEN-LAST:event_typeSearchBtnActionPerformed

    private boolean serialTxtProcess() {
        boolean isOK = true;
        if(searchTxt.getText().equals("") || Check.checkSerial(searchTxt.getText()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Mã sản phẩm không tồn tại !!!");
            searchTxt.requestFocus();
            return isOK = false;
        } else {
            serial = searchTxt.getText();
            return isOK;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField ceramicStuffTxt;
    private javax.swing.JButton dateSearchBtn;
    private javax.swing.JButton dateSortDBtn7;
    private javax.swing.JButton dateSortIBtn6;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField electronicStuffTxt;
    private javax.swing.JButton exportBtn;
    private javax.swing.JTextField foodStuffTxt;
    private javax.swing.JButton importBtn;
    private javax.swing.JButton invenSortDBtn6;
    private javax.swing.JButton invenSortIBtn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastTxt;
    private javax.swing.JTextField maxTxt;
    private javax.swing.JTextField maxTxt1;
    private javax.swing.JTextField minTxt;
    private javax.swing.JTextField minTxt1;
    private javax.swing.JTextField oldTxt;
    private javax.swing.JButton priceSearchBtn;
    private javax.swing.JButton priceSearchBtn1;
    private javax.swing.JButton priceSortDBtn5;
    private javax.swing.JButton priceSortIBtn4;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton serialSortDBtn4;
    private javax.swing.JButton serialSortIBtn3;
    private javax.swing.JTable showTbl;
    private javax.swing.JTextField totalPriceTxt;
    private javax.swing.JTextField totalStuffTxt;
    private javax.swing.JComboBox<String> typeChoiceBox;
    private javax.swing.JButton typeSearchBtn;
    private javax.swing.JButton typeSortDBtn;
    private javax.swing.JButton typeSortIBtn;
    // End of variables declaration//GEN-END:variables
    private boolean minTxtProcess()
    {
        boolean isOK = true;
        try {
            min = Long.parseLong(minTxt.getText());
        } catch (Exception e) {
            minTxt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn mức giá hoặc mức giá không hợp lệ!!!");
            minTxt.requestFocus();
            return isOK = false;
        }
        return isOK;
    }

    private boolean maxTxtProcess()
    {
        boolean isOK = true;
        try {
            max = Long.parseLong(maxTxt.getText());
        } catch (Exception e) {
            maxTxt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn mức giá hoặc mức giá không hợp lệ!!!");
            maxTxt.requestFocus();
            return isOK = false;
        }
        return isOK;
    }
    
    private boolean oldDateTxtProcess() {
        boolean isOK = true;
        String importDateString = oldTxt.getText();
        if(importDateString.equals("")) {
            oldTxt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Bạn nhập không đúng định dạng!!!");
            oldTxt.requestFocus();
            return isOK = false;
        } else {
            oldDate = FormatDate.nhapNgay(importDateString);
            return isOK;         
        }      
    }
     
    private boolean lastDateTxtProcess() {
        boolean isOK = true;
        String importDateString = lastTxt.getText();
        if(importDateString.equals("")) {
            lastTxt.setText("");
            JOptionPane.showMessageDialog(rootPane, "Bạn nhập không đúng định dạng!!!");
            lastTxt.requestFocus();
            return isOK = false;
        } else {
            lastDate = FormatDate.nhapNgay(importDateString);
            return isOK;         
        }      
    }
    
    private boolean typeChoiceProcess() {
        boolean isOK = true;
        if(typeChoiceBox.getSelectedItem().equals("Loại")) {
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn loại sản phẩm");
            typeChoiceBox.requestFocus();
            return isOK = false;
        } else {
            return isOK;
        }  
    }
        
}

